"""Normalized, human-readable fingerprint of the handbook web page.

The generated DOCX and PDF are not byte-reproducible (both embed build
timestamps), so they cannot tell CI whether the web page changed. The
snapshot can: it records only what feeds the document - the contacts, the
profile images and the body blocks - one block per line, so a web edit shows
up as a readable line diff in the refresh pull request.
"""
import hashlib
import os

from handbook_generator.builder import HandbookBuilder

HEADER = (
    "<!-- Generated by handbook_generator; do not edit by hand. "
    "A change here means the web page changed and the handbook is regenerated. -->"
)


def _sha256(path):
    if not path or not os.path.exists(path):
        return "missing"
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def _in_callout(element):
    parent = element.parent
    while parent is not None:
        if parent.name == "section" and "cke-callout" in (parent.get("class") or []):
            return True
        parent = parent.parent
    return False


def _format_block(element, text):
    text = " ".join(text.split())
    if not text:
        return None
    name = element.name or ""
    if name in ("h1", "h2", "h3", "h4", "h5", "h6"):
        return "#" * int(name[1]) + " " + text
    if name == "li":
        return "- " + text
    if _in_callout(element):
        return "> " + text
    return text


def build_snapshot(scraper_data, body_content, year):
    """Returns the snapshot text for the given scrape."""
    lines = [
        HEADER,
        "",
        f"year: {year}",
        f"chair: {scraper_data.get('chair_name')}",
        f"chair_image_sha256: {_sha256(scraper_data.get('chair_img_path'))}",
        f"dgs: {scraper_data.get('dgs_name')}",
        f"dgs_image_sha256: {_sha256(scraper_data.get('dgs_img_path'))}",
        "",
    ]
    # Same flattening the builder syncs against, so the snapshot changes
    # exactly when the builder would see different input.
    blocks = HandbookBuilder._flatten_html_blocks(body_content)
    for element, text in blocks:
        line = _format_block(element, text)
        if line:
            lines.append(line)
    return "\n".join(lines) + "\n"


def snapshot_differs(path, text):
    """True when the snapshot at path is missing or differs from text."""
    if not os.path.exists(path):
        return True
    with open(path, encoding="utf-8") as f:
        return f.read() != text


def write_snapshot(path, text):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
